<a href="https://colab.research.google.com/github/denishkanani/Deep-Learning-With-PyTorch/blob/main/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pip

In [2]:
!pip list

Package                   Version
------------------------- -----------------
absl-py                   1.4.0
accelerate                1.13.0
aiofiles                  25.1.0
aiohappyeyeballs          2.6.1
aiohttp                   3.13.4
aiosignal                 1.4.0
altair                    5.5.0
annotated-doc             0.0.4
annotated-types           0.7.0
anyio                     4.13.0
anywidget                 0.9.21
apsw                      3.51.3.0
apswutils                 0.1.2
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
array_record              0.8.3
arrow                     1.4.0
attrs                     26.1.0
audioread                 3.1.0
backcall                  0.2.0
beartype                  0.22.9
beautifulsoup4            4.13.5
betterproto               2.0.0b6
bleach                    6.3.0
blinker                   1.4
blis                      1.3.3
catalogue                 2.0.10
certifi                   2026.2.25
cffi    

In [3]:
import torch
import numpy as np

## Lists

In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## NumPy Array

In [9]:
np1 = np.random.rand(3,4)
np1.dtype

dtype('float64')

In [8]:
np1

array([[0.43725128, 0.8648512 , 0.26697847, 0.38317812],
       [0.19947009, 0.82555008, 0.51787725, 0.77831158],
       [0.24591311, 0.60577628, 0.79796823, 0.431669  ]])

## Tensor

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.3983, -0.1850,  0.0074,  0.7879],
        [ 0.7216, -1.1093,  0.4381, -1.0266],
        [-1.2352,  0.4717, -1.0374, -0.4139]])

In [13]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor out of numpy array

In [14]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8817, 0.7881, 0.9938, 0.3710],
        [0.2118, 0.1944, 0.8372, 0.3279],
        [0.2555, 0.1350, 0.4282, 0.2987]], dtype=torch.float64)