<a href="https://colab.research.google.com/github/denishkanani/Deep-Learning-With-PyTorch/blob/main/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pip

In [2]:
import torch
import numpy as np

## Lists

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## NumPy Array

In [4]:
np1 = np.random.rand(3,4)
np1.dtype

dtype('float64')

In [5]:
np1

array([[0.19599222, 0.98460573, 0.9574438 , 0.95831221],
       [0.57463597, 0.58050981, 0.38737515, 0.98228158],
       [0.88129447, 0.00966615, 0.42166953, 0.02353381]])

## Tensor

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.9567,  1.0267,  0.5060,  0.6600],
        [-0.2767, -1.4171, -1.3672, -1.3255],
        [ 1.0288,  0.2400,  1.2204,  1.6894]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor out of numpy array

In [8]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1960, 0.9846, 0.9574, 0.9583],
        [0.5746, 0.5805, 0.3874, 0.9823],
        [0.8813, 0.0097, 0.4217, 0.0235]], dtype=torch.float64)

## Tensor Oprations

In [9]:
import torch

In [10]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Reshape and View
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
# Reshape if we don't know the number of items using -1
my_tensor2 = torch.arange(10)
my_tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_tensor2 = my_tensor2.reshape(2,-1)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_tensor3 = torch.arange(10)
my_tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_tensor4 = my_tensor3.view(2,5)
my_tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
# With reshape and view, they will update
my_tensor5 = torch.arange(10)
my_tensor5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_tensor6 = my_tensor5.reshape(2,5)
my_tensor6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_tensor5[1] = 23

In [19]:
my_tensor6

tensor([[ 0, 23,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [20]:
# Slices
my_tensor7 = torch.arange(10)
my_tensor7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor7[7]

tensor(7)

In [22]:
# Grab Slice
my_tensor8 = my_tensor7.reshape(5,2)
my_tensor8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [23]:
my_tensor8[:,1]

tensor([1, 3, 5, 7, 9])

In [24]:
my_tensor8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## Tensor Math

In [25]:
import torch
import numpy as np

In [26]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [27]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [28]:
# Addition Langhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [29]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [30]:
# Sub Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [31]:
# Multipication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [32]:
# Mul longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [33]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [34]:
# Div longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [35]:
# Remainder Module
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [36]:
# Remainder Module
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [37]:
# Exponents / Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [38]:
# Another Way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [39]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [40]:
tensor_a

tensor([1, 2, 3, 4])

In [41]:
# Tensor_a = Tensor_a + Tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [42]:
tensor_a

tensor([ 6,  8, 10, 12])

## Simple Neural Network

In [43]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [44]:
# Create a Model Class that inherits nn.module
class Model(nn.Module):
  def __init__(self,in_features=4,h1=8,h2=9,out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features,h1)
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2,out_features)
  def forward(self, X):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)
    return x

In [45]:
# Pick a manual Seed for randomization
torch.manual_seed(13)
# Create an instance of the model
model = Model()