<a href="https://colab.research.google.com/github/denishkanani/Deep-Learning-With-PyTorch/blob/main/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pip

In [3]:
import torch
import numpy as np

## Lists

In [50]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## NumPy Array

In [9]:
np1 = np.random.rand(3,4)
np1.dtype

dtype('float64')

In [8]:
np1

array([[0.43725128, 0.8648512 , 0.26697847, 0.38317812],
       [0.19947009, 0.82555008, 0.51787725, 0.77831158],
       [0.24591311, 0.60577628, 0.79796823, 0.431669  ]])

## Tensor

In [48]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0974,  0.8402,  0.5276, -1.5912],
        [ 1.3474,  1.2028,  0.0204, -1.0817],
        [ 1.5186, -0.0683, -1.1245, -1.5953]])

In [49]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor out of numpy array

In [67]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8817, 0.7881, 0.9938, 0.3710],
        [0.2118, 0.1944, 0.8372, 0.3279],
        [0.2555, 0.1350, 0.4282, 0.2987]], dtype=torch.float64)

## Tensor Oprations

In [51]:
import torch

In [52]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# Reshape and View
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [54]:
# Reshape if we don't know the number of items using -1
my_tensor2 = torch.arange(10)
my_tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
my_tensor2 = my_tensor2.reshape(2,-1)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [56]:
my_tensor3 = torch.arange(10)
my_tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
my_tensor4 = my_tensor3.view(2,5)
my_tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
# With reshape and view, they will update
my_tensor5 = torch.arange(10)
my_tensor5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
my_tensor6 = my_tensor5.reshape(2,5)
my_tensor6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [60]:
my_tensor5[1] = 23

In [61]:
my_tensor6

tensor([[ 0, 23,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [62]:
# Slices
my_tensor7 = torch.arange(10)
my_tensor7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
my_tensor7[7]

tensor(7)

In [64]:
# Grab Slice
my_tensor8 = my_tensor7.reshape(5,2)
my_tensor8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [65]:
my_tensor8[:,1]

tensor([1, 3, 5, 7, 9])

In [66]:
my_tensor8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## Tensor Math

In [3]:
import torch
import numpy as np

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
# Addition Langhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
# Sub Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [11]:
# Multipication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
# Mul longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Div longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Remainder Module
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
# Remainder Module
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponents / Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [18]:
# Another Way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [20]:
tensor_a

tensor([1, 2, 3, 4])

In [21]:
# Tensor_a = Tensor_a + Tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([ 6,  8, 10, 12])